name: VDT2023_Midterm
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx 
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vdt-frontend
            ${{ secrets.DOCKERHUB_USERNAME }}/vdt-backend

      - name: Build and Push Docker Frontend Image
        uses: docker/build-push-action@v2
        id: docker_build_frontend
        with:
          context: ./web_crud/front-end/
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{ steps.meta.outputs.tags[0] }}

      - name: Verify image front-end
        run: echo ${{steps.docker_build_frontend.outputs.digest}}
  
      - name: Build and Push Docker Backend Image
        uses: docker/build-push-action@v2
        id: docker_build_backend
        with:
          context: ./web_crud/python/
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{ steps.meta.outputs.tags[1] }}

      - name: Verify image back-end
        run: echo ${{steps.docker_build_backend.outputs.digest}}
    